# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - avoid_print
    - prefer_const_constructors
    - prefer_final_locals
    - avoid_redundant_argument_values
    - prefer_const_literals_to_create_immutables
    - prefer_typing_uninitialized_variables
    - use_late_for_private_fields_and_variables
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_this
    - prefer_single_quotes
    - camel_case_types
    - constant_identifier_names
    - non_constant_identifier_names

analyzer:
  exclude:
    # Exclude generated files from linting
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "lib/gen/**"